name: Trigger auto deployment for cyber-ai-online

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cyber-ai-online-AutoDeployTrigger-010ba13e-0eef-4ed7-9e74-9377c2be920d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cyberai.azurecr.io
          username: ${{ secrets.CYBERAIONLINE_REGISTRY_USERNAME }}
          password: ${{ secrets.CYBERAIONLINE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cyberai.azurecr.io/cyber-ai-online:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CYBERAIONLINE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cyber-ai-online -g container-apps --server cyberai.azurecr.io --username  ${{ secrets.CYBERAIONLINE_REGISTRY_USERNAME }} --password ${{ secrets.CYBERAIONLINE_REGISTRY_PASSWORD }}
            az containerapp update -n cyber-ai-online -g container-apps --image cyberai.azurecr.io/cyber-ai-online:${{ github.sha }}
